variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  GIT_STRATEGY: clone

cache:
  paths:
    - .cache/pip
    - ${PRE_COMMIT_HOME}

stages:
  - lint
  - test
  - doc
  - build

.except-default: &except-default
  except:
    - tags

.python_version: &python-base-env
  <<: *except-default
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip setuptools
    - python -m pip install --upgrade -e . --group dev

.python_matrix:
  <<: [*except-default, *python-base-env]
  parallel:
    matrix: &python-support-matrix
      - PYTHON_VERSION:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
  image: python:$PYTHON_VERSION

.pre-commit:
  <<: [*except-default, *python-base-env]
  before_script:
    - python -m pip install pre-commit

.tox:
  <<: [*except-default, *python-base-env]
  before_script:
    - python -m pip install --upgrade tox

.tox_py_matrix:
  extends: .tox
  parallel:
    matrix: *python-support-matrix
  image: python:$PYTHON_VERSION

pre-commit mypy:
  stage: lint
  extends: .pre-commit
  cache:
    paths:
      - .mypy_cache/
  script:
    - python -m pip install mypy-gitlab-code-quality
    - python -m pre_commit run --all-files --verbose --hook-stage manual mypy || true
    - mypy-gitlab-code-quality < .mypy.out > gl-qa-report-mypy.json
  artifacts:
    reports:
      codequality: gl-qa-report-mypy.json

pre-commit strict:
  stage: lint
  extends: .pre-commit
  variables:
    # commitizen: waiting confirmation from project this is the expected standard
    # flake8: handled by custom scripts for now
    # mypy: run in another stage
    SKIP: commitizen,flake8,mypy
  script:
    - python -m pre_commit run --all-files --verbose --hook-stage manual

lint:
  stage: lint
  extends: .python_version
  script:
    - ./tools/pyflakes.sh
  artifacts:
    reports:
      codequality: gl-qa-report-flake8.json

lint strict:
  stage: lint
  extends: .python_version
  script:
    - ./tools/pyflakes-strict.sh
  artifacts:
    reports:
      codequality: gl-qa-report-flake8-strict.json

bandit:
  stage: lint
  extends: .tox
  script:
    - tox run -e bandit

check modules:
  stage: test
  extends: .python_matrix
  script:
    - .ci/check_modules.sh

test:
  stage: test
  extends: .tox_py_matrix
  script:
    - tox run -e py${PYTHON_VERSION//.} -- -sv --cov-report=xml:coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

doc:
  stage: doc
  extends: .tox
  script:
    - tox run -e docs
  artifacts:
    name: "Documentation from $CI_COMMIT_REF_SLUG"
    paths:
      - docs/build/html
    expire_in: 7 days

build:
  stage: build
  extends: .tox
  script:
    - tox run -e build
  artifacts:
    name: "Python sdist and wheel from $CI_COMMIT_REF_SLUG"
    paths:
      - dist
    expire_in: 7 days

local install:
  stage: build
  extends: .python_matrix
  script:
    - ./tools/local_install.sh --local-modules ~/bin
