variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  GIT_STRATEGY: clone

cache:
  paths:
    - .cache/pip
    - ${PRE_COMMIT_HOME}

stages:
  - lint
  - test
  - doc
  - build

.except-default: &except-default
  except:
    - tags

.python_version:
  <<: *except-default
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip setuptools
    - python -m pip install --upgrade -r requirements-dev.txt
    - python -m pip install -e .

.pre-commit:
  <<: *except-default
  image: python:3.9
  before_script:
    - python -m pip install pre-commit

pre-commit mypy:
  stage: lint
  extends: .pre-commit
  cache:
    paths:
      - .mypy_cache/
  script:
    - python -m pip install mypy-gitlab-code-quality
    - python -m pre_commit run --all-files --verbose --hook-stage manual mypy || true
    - mypy-gitlab-code-quality < .mypy.out > gl-qa-report-mypy.json
  artifacts:
    reports:
      codequality: gl-qa-report-mypy.json

pre-commit strict:
  stage: lint
  extends: .pre-commit
  variables:
    # commitizen: waiting confirmation from project this is the expected standard
    # flake8: handled by custom scripts for now
    # mypy: run in another stage
    SKIP: commitizen,flake8,mypy
  script:
    - python -m pre_commit run --all-files --verbose --hook-stage manual

lint:
  stage: lint
  extends: .python_version
  script:
    - ./tools/pyflakes.sh
  artifacts:
    reports:
      codequality: gl-qa-report-flake8.json

lint strict:
  stage: lint
  extends: .python_version
  script:
    - ./tools/pyflakes-strict.sh
  artifacts:
    reports:
      codequality: gl-qa-report-flake8-strict.json

bandit:
  extends: .python_version
  stage: lint
  script:
    - pip install bandit>=1.8.1
    - bandit -r woob
    - bandit -r modules
    - bandit -r contrib

check modules:
  stage: test
  extends: .python_version
  script:
    - .ci/check_modules.sh

test:
  stage: test
  extends: .python_version
  script:
    - ./tools/run_tests.sh --no-modules
    - coverage xml -o coverage.xml -i
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

doc:
  stage: doc
  extends: .python_version
  script:
    - make docs

build:
  stage: build
  extends: .python_version
  script:
    - pip install build twine
    - python -m build
    - twine check dist/*.whl

local install:
  stage: build
  extends: .python_version
  script:
    - ./tools/local_install.sh --local-modules ~/bin
