repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pycqa/isort.git
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-ast
        exclude: ^tools/(boilerplate/.*\.pyt|cookiecutter/)
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args:
          - --autofix
          - --indent=4
          - --no-sort
          - --trailing-commas

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.10.27
          - flake8-future-import==0.4.7
          - flake8-print==5.0.0
          - flake8-pyproject==1.2.2
        files: ^woob/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/google/yamlfmt.git
    rev: v0.14.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-Deprecated
          - types-python-dateutil
          - types-pyyaml
          - types-requests
          - types-simplejson
        files: ^woob/
        log_file: .mypy.out
